'use strict';

import * as THREE from 'three';

export function generateGcode(mode, layers, settings, modelCount) {
  const lines = [];
  const timestamp = new Date().toISOString().split('T')[0];

  lines.push('; Generated by FERROWORKER Slicer');
  lines.push('; Mode: ' + mode.toUpperCase());
  lines.push('; Date: ' + timestamp);
  lines.push('; Models: ' + modelCount);
  lines.push('G21 ; set units to mm');
  lines.push('G90 ; absolute positioning');

  if (mode === 'fdm') {
    generateFDMGcode(lines, layers, settings);
  } else if (mode === 'laser') {
    generateLaserGcode(lines, layers, settings);
  } else if (mode === 'cnc') {
    generateCNCGcode(lines, layers, settings);
  }

  return lines.join('\n') + '\n';
}

function generateFDMGcode(lines, layers, s) {
  lines.push('M82 ; absolute extrusion');
  lines.push('M107 ; fan off');
  lines.push('M140 S' + s.bedTemp + ' ; set bed temp');
  lines.push('M190 S' + s.bedTemp + ' ; wait for bed');
  lines.push('M104 S' + s.nozzleTemp + ' ; set hotend temp');
  lines.push('M109 S' + s.nozzleTemp + ' ; wait for hotend');
  if (s.chamberTemp > 0) {
    lines.push('M141 S' + s.chamberTemp + ' ; set chamber temp');
    lines.push('M191 S' + s.chamberTemp + ' ; wait for chamber');
  }
  lines.push('G28 ; home all axes');
  lines.push('G29 ; auto bed level (if equipped)');
  lines.push('G1 Z5 F3000 ; lift nozzle');
  lines.push('G1 X60 Y60 F' + (s.travelSpeed * 60) + ' ; wipe pos');
  lines.push('G1 Z0.3 F3000');
  for (let i = 0; i < 3; i++) {
    lines.push('G1 X20 E10 F' + (s.printSpeed * 60));
    lines.push('G1 Y75 E10');
    lines.push('G1 X60 E10');
    lines.push('G1 Y45 E10');
  }
  lines.push('G1 Z' + s.layerHeight.toFixed(2) + ' F3000');
  lines.push('M106 S' + Math.round(s.fanSpeed * 2.55) + ' ; fan on');

  if (s.pressureAdv > 0) {
    lines.push('M900 K' + s.pressureAdv.toFixed(3) + ' ; pressure advance');
  }

  let ePos = 0;
  for (let l = 0; l < layers.length; l++) {
    const layer = layers[l];
    lines.push(';LAYER ' + l);
    lines.push('G1 Z' + layer.z.toFixed(3) + ' F' + (Math.max(s.travelSpeed, 10) * 60));

    for (const poly of layer.polygons) {
      if (poly.length < 3) continue;
      for (let p = 0; p < s.perimeters; p++) {
        const offset = p * s.lineWidth * 0.5;
        const pts = offsetPolygon(poly, offset);
        if (pts.length < 3) continue;
        lines.push('G0 X' + pts[0].x.toFixed(3) + ' Y' + pts[0].y.toFixed(3) + ' F' + (s.travelSpeed * 60));
        for (let i = 1; i < pts.length; i++) {
          ePos += calcExtrusion(pts[i-1], pts[i], s.lineWidth, s.layerHeight, s.flowRate);
          lines.push('G1 X' + pts[i].x.toFixed(3) + ' Y' + pts[i].y.toFixed(3) + ' E' + ePos.toFixed(5) + ' F' + (s.printSpeed * 60));
        }
        ePos += calcExtrusion(pts[pts.length-1], pts[0], s.lineWidth, s.layerHeight, s.flowRate);
        lines.push('G1 X' + pts[0].x.toFixed(3) + ' Y' + pts[0].y.toFixed(3) + ' E' + ePos.toFixed(5));
      }
      if (s.infill > 0) {
        const infill = generateInfill(poly, s.lineWidth, s.infill / 100, s.infillPattern);
        infill.forEach(seg => {
          lines.push('G0 X' + seg[0].x.toFixed(3) + ' Y' + seg[0].y.toFixed(3) + ' F' + (s.travelSpeed * 60));
          ePos += calcExtrusion(seg[0], seg[1], s.lineWidth, s.layerHeight, s.flowRate);
          lines.push('G1 X' + seg[1].x.toFixed(3) + ' Y' + seg[1].y.toFixed(3) + ' E' + ePos.toFixed(5) + ' F' + (s.printSpeed * 60));
        });
      }
    }
  }
  lines.push(';END');
  lines.push('M106 S0');
  lines.push('G91');
  lines.push('G1 Z10 F3000');
  lines.push('G90');
  lines.push('G28 X Y');
  lines.push('M104 S0');
  lines.push('M140 S0');
  lines.push('M84');
  lines.push('M107');
}

function generateLaserGcode(lines, layers, s) {
  lines.push('M3 S0 ; laser off');
  lines.push('G28 ; home');
  lines.push('G0 Z5 F3000');
  for (let p = 0; p < s.laserPasses; p++) {
    lines.push('; Pass ' + (p + 1));
    for (let l = 0; l < layers.length; l++) {
      const layer = layers[l];
      lines.push(';LAYER ' + l);
      for (const poly of layer.polygons) {
        if (poly.length < 3) continue;
        lines.push('G0 X' + poly[0].x.toFixed(3) + ' Y' + poly[0].y.toFixed(3) + ' F' + s.laserSpeed);
        const pwm = s.laserMode === 'cut' ? Math.min(s.laserPWM, Math.round(s.laserPower * 2.55)) :
                    s.laserMode === 'engrave' ? Math.min(s.laserPWM, Math.round(s.laserPower * 1.5)) :
                    Math.min(s.laserPWM, Math.round(s.laserPower * 2.55));
        lines.push('M3 S' + pwm);
        for (let i = 1; i < poly.length; i++) lines.push('G1 X' + poly[i].x.toFixed(3) + ' Y' + poly[i].y.toFixed(3) + ' F' + s.laserSpeed);
        lines.push('M5');
        lines.push('G4 P100');
      }
    }
  }
  lines.push('G0 X0 Y0 Z20');
  lines.push('M5');
  lines.push('M2');
}

function generateCNCGcode(lines, layers, s) {
  lines.push('M3 S' + s.spindleSpeed + ' ; spindle on');
  lines.push('G28 ; home');
  lines.push('G43 H1 T1 ; tool offset');
  lines.push('G4 P2000 ; wait spindle');
  lines.push('G0 Z50 F' + (s.travelSpeed * 60));
  for (let l = 0; l < layers.length; l++) {
    const layer = layers[l];
    lines.push(';LAYER ' + l + ' Z=' + layer.z.toFixed(3));
    for (const poly of layer.polygons) {
      if (poly.length < 3) continue;
      for (let i = 0; i < poly.length - 1; i++) {
        lines.push('G0 X' + poly[i].x.toFixed(3) + ' Y' + poly[i].y.toFixed(3) + ' F' + (s.travelSpeed * 60));
        lines.push('G1 Z' + layer.z.toFixed(3) + ' F' + (s.plungeRate * 60));
        lines.push('G1 X' + poly[i+1].x.toFixed(3) + ' Y' + poly[i+1].y.toFixed(3) + ' F' + (s.feedRate * 60));
      }
    }
  }
  lines.push('G0 Z50');
  lines.push('M5');
  lines.push('G28 Z');
  lines.push('G28 X Y');
  lines.push('M2');
}

function calcExtrusion(a, b, lineWidth, layerHeight, flowRate) {
  const dist = Math.sqrt((b.x - a.x) ** 2 + (b.y - a.y) ** 2);
  const flow = (flowRate || 100) / 100;
  return dist * lineWidth * layerHeight * 0.05 * flow;
}

function offsetPolygon(poly, offset) {
  if (poly.length < 3) return poly;
  const result = [];
  for (let i = 0; i < poly.length; i++) {
    const prev = poly[(i - 1 + poly.length) % poly.length];
    const curr = poly[i];
    const next = poly[(i + 1) % poly.length];
    const dx1 = curr.x - prev.x, dy1 = curr.y - prev.y;
    const dx2 = next.x - curr.x, dy2 = next.y - curr.y;
    const len1 = Math.sqrt(dx1*dx1 + dy1*dy1) || 1;
    const len2 = Math.sqrt(dx2*dx2 + dy2*dy2) || 1;
    const nx = (-dy1/len1 + -dy2/len2) / 2, ny = (dx1/len1 + dx2/len2) / 2;
    const nlen = Math.sqrt(nx*nx + ny*ny) || 1;
    result.push({ x: curr.x + (nx/nlen) * offset, y: curr.y + (ny/nlen) * offset });
  }
  return result;
}
